### PR TITLE
Fix for #407

### PR DESCRIPTION
**Pull request by babdab9**
This PR fixes issue #407

### CODE REVIEW

**Comment by knight-ryu12** [comment]
wew…

**Comment by babdab9** [comment]
I do not know all the commits lol. I just did the last one

**Comment by Frederikam** [comment]
Do not merge into `development`. That branch is bound to be deleted in favour of `dev`

**Comment by Frederikam** [comment]
Seems changing the base didn't help.

**Comment by babdab9** [comment]
so I should re request in `dev`? @Fredrikam

**Comment by Frederikam** [comment]
Yes

**Pull request closed without merging**
