### PR TITLE
Make FredBoat ignore messages from other bots

### PR DESCRIPTION
**Pull request by Vandesdelca32**
Get FredBoat to ignore messages sent by other bots.

I have not tested this code. But it should be all that is needed to stop Issue #228, unless it listens elsewhere as well.

### CODE REVIEW

**Comment by RealKC** [comment]
@Vandesdelca32 I just noticed you are trying to merge into master, you need to merge into development(you may need to cherrypick the PR if when trying to merge into development commits from master appear).

**Comment by Vandesdelca32** [comment]
Changed the target of the PR... It looks like it should still be okay to merge into this branch, only changes a couple of lines in /src/main/java/fredboat/event/EventListenerSelf.java

**Comment by Shredder121** [comment]
>`event.getAuthor().equals(event.getJDA().getSelfUser())`
>`event.getAuthor().isBot()`

I think these are equivalent in FredBoat's case?
What do you think? @napstr

**Comment by Vandesdelca32** [comment]
@Shredder121 The first appears to refer to the bot itself's message, where as the second is the case for any other bots that are posting, not just FredBoat.

**Comment by Shredder121** [comment]
I thought we also dropped our own events, and since `isBot()` is true when it's the self user I figured we could collapse it.
But never mind.

**Comment by Vandesdelca32** [comment]
I don't even know why that didn't cross my mind, sorry D:

**Comment by napstr** [comment]
@Shredder121 they are, or rather, `event.getAuthor().equals(event.getJDA().getSelfUser())` will never be reached when `event.getAuthor().isBot()` already returns.

@Vandesdelca32 can you please move your addition below the statement where you placed it currently?

**Pull request merged**
