### PR TITLE
Added Text Faces, moved some commands around

### PR DESCRIPTION
**Pull request by RealKC**
If `;;dealwithit` doesn't work like it's supposed to, I blame Shredder >_>(It should print `(•_•) ( •_•)>⌐■-■ (⌐■_■)`.).

### CODE REVIEW

**Comment by Shredder121** [comment]
And I'm sure it's going to work. >_>

**Comment by Frederikam** [comment]
There was a typo `TextCOmmand`

**Comment by RealKC** [comment]
Fixed it

**Comment by RealKC** [comment]
Pretty sure you can merge it now

**Pull request merged**
