### PR TITLE
[WIP] Feature/persistent tracklists (closes #139)

### LINKED ISSUE #139: Fix persistent queues
We have a persistent queue system, only that's it's broken and thus disabled.

I'm thinking of rewriting this, but with an SQL table instead of the filesystem. Thoughts?

### PR DESCRIPTION
**Pull request by napstr**
This is like #236 but with persistent guild player settings and track lists.

ToDos before merging:

- [ ] get some reviews :3
- [ ] update language submodule

### CODE REVIEW

**Comment by napstr** [comment]
ToDos before merging:

[ ] get some reviews :3
[ ] update language submodule

**Comment by Frederikam** [comment]
Welp. Have fun I guess.
image

**Comment by napstr** [comment]
No biggie, most were conflicts in the imports.

**Comment by napstr** [comment]
image
:100:

**Comment by RealKC** [comment]
Press F to pay respects.

**Comment by napstr** [comment]
@Frederikam I petition to test this on cutting edge.

**Comment by napstr** [comment]
Just the weekly rebase coming through :eyes:

**Comment by napstr** [comment]
This PR will be rethonked, and probably split up and partly reworked.

**Comment by itsaphel** [comment]
@Frederikam @napstr 

Any interest in working on this PR? I'd like to see song persistence (e.g. if you like some songs, you can save them and you have a nice list built in). I'd be happy to contribute to see this in the bot, provided it's available for the free version of the bot.

**Pull request closed without merging**
