### PR TITLE
[WIP] First pass on adding custom aliases

### PR DESCRIPTION
**Pull request by napstr**
Started off feeling like writing a nice little feature.
Parsing and entity stuff was trivial enough, and it works perfectly fine, but my head is spinning from trying to give it a decent UX.

- [ ] ~~merge after #436 and #439~~ / check migration versioning
- [ ] resolve dohz //todos
- [ ] (probably) write a docs page

### CODE REVIEW

**Comment by napstr** [comment]
related to #168

**Comment by napstr** [comment]
Please have a look:

Using an alias to have FredBoat say something:
image
Adding an essential alias which the bot creators failed to add:
image
Deleting an alias:
image
Aliases can be edited for a entire guild saying `guild` or `here` in the command:
image

**Comment by napstr** [comment]
Some Questions:
1. Should aliases overwrite official FredBoat commands?
I think they should not. While it's funny to do so for some commands, we definitely have commands that we would not want to be overwritten.

2. If a guild and a user have defined the same alias, which one should FredBoat respond to?
I would think the guild alias takes precedence over an alias a user has defined for themselves.

**Comment by napstr** [comment]
I'll take the lack of discussion around this to indicate that my I am free to answer my questions with whatever I prefer, and that the design is fine as it is. I shall bring this PR back up to speed with the current code and merge it then.

**Comment by Frederikam** [comment]
>If a guild and a user have defined the same alias, which one should FredBoat respond to?
I would think the guild alias takes precedence over an alias a user has defined for themselves.

Why? A user's alias would be more specific. Furthermore, the user might not be aware of what aliases a guild is using

**Comment by Frederikam** [comment]
It would be inconvenient and probably also rude if some user was to operate the bot in Danish when the accepted language of a guild might be English.

However, I think this isn't such a big a deal since it is unlikely that we are going to have many conflicts. Perhaps it is even confusing that both users and guilds have aliases.

**Comment by napstr** [comment]
Someone else feel free to pick this up.

**Pull request closed without merging**
