### PR TITLE
Implemented multi-select option

### PR DESCRIPTION
**Pull request by SuhanKoh**
This is for #114

### CODE REVIEW

**Comment by SuhanKoh** [comment]
Question: Not sure if we should change the i18n for 'selectSuccess', currently when you select multiple songs, it will print the first one.

**Comment by napstr** [comment]
Hi, I would appreciate it if you could please not reformat whitespace unrelated to the lines you are changing in your PRs as it's a possible source of unnecessary conflicts.

**Comment by napstr** [comment]
If you are lazy like me you can achieve that by using the IntelliJ SaveActions plugin with a ticked "reformat only changed code" option.
image or manually staging hunks when creating the commit and discarding those lines that the reformatter was too eager to touch.

**Comment by napstr** [comment]
This isn't in a working state at all. Here are a few broken things, this is most likely not a full list, as I didn't event try breaking it on purpose.

Detection not working with the numbered alias:
image

Using the number alias selects only 1 instead of several:
image

Unhandled exceptions:
image

No response to the user after selecting:
image


Please test your code more extensively.

**Comment by SuhanKoh** [comment]
Fix the following

- [ ] <<1,2,3,4,5 

- [ ] <<1 2 3 4 5 should have included all 5 searches

- [ ] <<p 1 2 3 should not throw error

- [ ] <<p 1,2,3,4,5 should not have duplicated 1s.

**Comment by SuhanKoh** [comment]
@napstr So ;;p 1 2 3 4 5 will queue all 5 songs? based on #114 it specified comma

**Comment by napstr** [comment]
> @napstr So ;;p 1 2 3 4 5 will queue all 5 songs? based on #114 it specified comma

That's just one example.
Personally I would suggest going as far as allowing 12345 or 145 or 314 or whatever combinations.

**Comment by SuhanKoh** [comment]
Should the command notify if one of the selection is dropped? eg: ``<<1 23 2 4`` 23 would be ignored?

**Comment by napstr** [comment]
I think telling the user which tracks were selected is an easy and transparent way to tell them what's happening.

Example:
Input:
```
;;2 1 5
```
Output:
```
Song #2 has been selected: Some song (02:10)
Song #1 has been selected: Whatever (04:52)
Song #5 has been selected: Another song (13:28)
```

**Comment by SuhanKoh** [comment]
Should I change the output to Embed then? because otherwise multi-select won't look good as the first song get printed on first line

**Comment by SuhanKoh** [comment]
Print out example:
capture

**Pull request merged**
