### PR TITLE
Collapse the screenshots in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Shredder121**
Stub, but how is this?
For if we also want to add screenshots for NetBeans, or make the `CONTRIBUTING.md` just really heavy on screenshots in general?

### CODE REVIEW

**Comment by Shredder121** [comment]
In the diff you can click on the "rich view diff" to see what it becomes.
image
You have to scroll down quite a lot, past the 'deleted' (red) bit.

**Comment by napstr** [comment]
Neat markdown feature, wasn't aware of this.

Looks good. Maybe change the summary to include "Click me" somewhere, as it looks like it's a bit hard to realize that it's clickable?

**Comment by Shredder121** [comment]
It's not so much of a markdown feature, but more of an HTML feature that markdown whitelists, so it can be serialized directly.
But yeah, thought it would be good to break up the very long passage(s).

**Comment by Shredder121** [comment]
Not quite sure where to place it, and markup doesn't work, unless we make it a markdown block again.
Although then it becomes a `<p>` and the summary element doesn't work anymore.

Also, I saw some typos as well? For example:
```
> Pay special attention to the bottom if that screenshot.
```

**Comment by napstr** [comment]
Typos are a byproduct of the suboptimal design choice of natural languages not being strongly typed. Feel free to fix on sight :mag_right: 

As for the visibilty I'd leave an empty line both above and below the fold, that should be good enough.

**Comment by napstr** [comment]
I hope you like to share PRs. :upside_down_face:

**Comment by napstr** [comment]
Oh ffs the CLA bot wins.

**Comment by RealKC** [comment]
lol the CLA bot really loves to complain

**Comment by Frederikam** [comment]
>Oh ffs the CLA bot wins.

Victory!

**Pull request merged**
