### PR TITLE
Compact command registry

### PR DESCRIPTION
**Pull request by Shredder121**
I noticed while hardcoding in more aliases, that typos can be made a little too easily.
By including it in the call to `registerCommand` you don't have to type the command twice, `3`x, `4`x, `n`x.

Also, let me know if the original parameter ordering should be preserved, or the one in my first commit is better, should you want to merge this.
(then I can either drop or squash the last commit)

### CODE REVIEW

**Comment by Shredder121** [comment]
Signed 👍

**Comment by napstr** [comment]
Looks good to me.

**Comment by Frederikam** [comment]
This looks great! I like how you rearranged the parameters. It makes things more readable.

**Comment by Ritchie454** [comment]
This makes my slight OCD very happy, nice job 👍

**Comment by Shredder121** [comment]
> This looks great! I like how you rearranged the parameters.
i could have cleaned up the commits, so it was actually rearranged, or did you mean that it was fine like that?

**Comment by Shredder121** [comment]
*I secretly have a few other outstanding changes, but didn't get to commit them for some time.*
*But good to hear it is being received so well!*

**Comment by Frederikam** [comment]
>I could have cleaned up the commits, so it was actually rearranged, or did you mean that it was fine like that?

GitHub gives me the ability to squash before merging, which I did.

**Comment by Shredder121** [comment]
Then I assume the ordering is fine as it is now, good good. 👍

**Pull request merged**
