### PR TITLE
Allow BOT_ADMINs to use "Destroy" regardless of permissions

### LINKED ISSUE #231: BOT_ADMIN not overriding manage messages on ;;destroy
More or less what the title says, BOT_ADMIN cannot use ;;destroy without having a role for manage messages, I don't know if the requirement should be lifted, or if that requirement should stay, but be bypassed for BOT_ADMIN

### PR DESCRIPTION
**Pull request by Nanabell**
image
image
I left the "destroyDenied" message untouched as it does not really affect anyone but is Bot Admins.   
This fixes #231

### CODE REVIEW

**Comment by Nanabell** [comment]
On second thought should "ADMINS" also be allowed to use it? The issue only mentions BOT_ADMINS so i didn't think about it first

**Comment by napstr** [comment]
Admins of a discord server have the `Permission.MESSAGE_MANAGE`.

**Comment by Nanabell** [comment]
I was thinking about our PermissionLevel Admins since you don't have to have Discord Admin perms to have Fredboat Admin Perms

**Comment by napstr** [comment]
The destroy command can be used by anyone with `Permission.MESSAGE_MANAGE` (which includes discord  server admins) [first statement of the if clause] and the ~~bot owner~~ FredBoat admins (which includes the bot owner) [second statement of the clause, which is what gets changed in this PR].

Looks good to me.

**Comment by Nanabell** [comment]
I mean refer to Fred's screenshot in #231. i meant the ;;admin add <id> Admin not Discord admin or BOT_ADMINS

**Comment by napstr** [comment]
Might as well allow them too.

**Pull request merged**
