### PR TITLE
Refactoring of the music stack

### PR DESCRIPTION
**Pull request by napstr**
This cleans up everything weird going on in the music stack.

It builds on #235 

It should have been part of persistent track lists (and guild players), but I'm still working on their performance at scale.

### CODE REVIEW

**Comment by Frederikam** [comment]
If you provide a list of changes you've made it would make this easier to review.

**Comment by napstr** [comment]
Here's a list I've been keeping:

Fix bug introduced in #224 where the first skip in a guild after a restart would always be ignored
Fix issue #199
Fix missing checks where a user moving to a different channel would not trigger pausing, and a user moving into the channel from a different one would not trigger auto_resume, and FredBoat itself being moved around wouldn't react to it either.
Fix a bug where a bot user joining into the channel would trigger the autoresume
Do the skip announcement before the announcement of the next playing track.


Additionally:
More (efficient) methods have been defined for ITrackProvider and implemented in the SimpleTrackProvider. All shuffle and repeat related stuff is in the AbstractTrackProvider. GuildPlayer and AbstractPlayer are much more lean and methods have been given better names (there were like three playSomething methods including an infamous play0() one lol essentially doing very similar things). There was some confusion about which events happen when exactly and how (split tracks ending, skipping) and weird code written around to handle that which I stripped down. Errors loading a track (to play) would lead to no announcement and the player stopping, that's handled better now.

**Comment by Frederikam** [comment]
Just skimmed this. I noticed how you changed the IDs of the entities to longs. Is that not duplicate of #235? And does that not also mean that this cannot be merged before we update all FredBoat instances and migrate all the schemas?

**Comment by napstr** [comment]
Yes, that's why I opened #235 in advance, to not have it tangled up with other updates.
Tbh I probably found a different and better solution to it yesterday which would be to just generify IEntity and the id. That way we don't have to touch any existing tables. The desire to use longs instead of Strings as the main id comes from the Ratelimiter which holds a ton of objects in memory (I did some calculations back in the day...). The impact on other entities is marginal and switching them to longs is probably not worth the trouble if there is another way.

**Comment by napstr** [comment]
closed in favor of #245

**Pull request closed without merging**
