### PR TITLE
Changed the docker compose file to the correct branch on the Quarterdeck repo.

### PR DESCRIPTION
**Pull request by jtagt**

### CODE REVIEW

**Comment by napstr** [comment]
There is no "dev" channel.
The correct channel is right there in the file.

**Comment by napstr** [comment]
Also I don't understand why you're changing one of the component to the dev-channel, but not the other. The file does not make any sense that way, there is no stable v3 release of FredBoat either.

**Comment by jtagt** [comment]
I see. I close this PR since there was no issue with the docket-compose file.

**Comment by napstr** [comment]
If you need access to a backend in order to write client code, talk to me on Discord.

**Pull request closed without merging**
