### PR TITLE
Dockerize FredBoat + Postgres + ditch sqlite

### LINKED ISSUE #387: Clarify branch names
This came up more than once in internal discussions, so I'm opening an issue so that we can reach a decision.

Proposed changes:
- Rename master branch to `stable`, keep it protected as it is currently
- Make development branch the main branch of the repo so that github integrations (like closing issues once a PR is merged) work properly

@Shredder121 @Nanabell @Frederikam please check if I missed something and/or voice your opinion.

### PR DESCRIPTION
**Pull request by napstr**
Hi,

this PR dockerizes FredBoat and bundles it with Postgres via docker-compose. This is mainly meant as an alternative to the currently used SQlite db for selfhosters, but I wouldn't rule out using docker images in our production in the future.

Pros: We ditch the sqlitedb support for selfhosters which is a pain, because advanced postgres stuff can't be used else we risk stuff breaking functionality for selfhosters. Actually there is already broken functionality, namely the search cache. It is also quite annoying to test new things for both databases, both in terms of functionality and the giant gap of performance between the databases (example: sqlite doesn't allow more than 1 concurrent connection cause file locks).

Why I'm positive that being less db agnostic and embracing postgres is a good thing: It is currently in a good place as a performant allrounder database, for SQL, Json (via JSONB) and Pub/Sub (via Listen/Notify). The chances of encountering any deal breakers in the near to midterm future are very low in my opinion.

Cons:
~~Running FredBoat for selfhosters becomes not as simple as installing java, downloading a jar, creating a credentials file, and running it. Instead the process involves cloning the git repo, running a maven build, and installing docker and docker compose. We could possibly provide a convenience package download of just the jars and docker files and config/credentials files.~~
Instead of installing Java selfhosters need to install docker and compose. idk if thats a real con lol

todos:
- [x] explore CI capabilities of providing a convenience package download of jars + docker stuff + config/credentials files
- [x] test on windows
- [x] test on raspi
- [x] documentation of the commands (somewhat done already, but needs to be PRed to the website repo) https://github.com/FredBoat/fredboat.com/pull/14
- [x] Resolve #387

### CODE REVIEW

**Comment by napstr** [comment]
Oh if anyone wants to take this for a test ride, the command to start it all is
```
docker-compose up
```
from the project root directory. Make sure to have a FredBoat/config.yaml and FredBoat/credentials.yaml.

**Comment by Nanabell** [comment]
^and well... you need docker & docker compose lol

**Comment by napstr** [comment]
Any windows users care to try this out?
Here's the CI link:
https://ci.fredboat.com/guestAuth/repository/downloadAll/FredBoat_Build/.lastSuccessful?branch=refs/heads/feature/docker
Unpack that zip, copy credentials.yaml.example to credentials.yaml, add ur bot token.
Do `docker-compose up` and see if it works (look at the log for errors or run some db command like ;;config).

**Comment by napstr** [comment]
Just spun up a CentOS VPS and things worked flawlessly.

**Comment by napstr** [comment]
Works on my shitty win7 laptop from 2011, using the legacy docker toolbox.

One thing that didn't work is the database volume, I had to comment that out in the docker-compose. This just means that windows users can't easily backup their database but I don't consider that a huge issue since updates won't require destroying the database container.

If you are testing this on Win10 or similar and the db is erroring out when starting, try commenting out these two lines in the docker-compose.yaml:
```
#    volumes:
#      - ./.pg_data:/var/lib/postgresql/data
```

**Comment by SuhanKoh** [comment]
@napstr Tried the CI link on Windows 10 64-bit on docker version 17.09.0.

Gave this error (Also tried to comment and remove volumes instruction).

```
fredboatfeaturedocker_db_1 is up-to-date
Creating fredboatfeaturedocker_bot_1 ...
Creating fredboatfeaturedocker_bot_1 ... error

ERROR: for fredboatfeaturedocker_bot_1  Cannot create container for service bot: Drive has not been shared

ERROR: for bot  Cannot create container for service bot: Drive has not been shared
ERROR: Encountered errors while bringing up the project.
```

I also tried hooking "Shared Drives" to one of my hard disk drive, still gave the same error message.

**Comment by napstr** [comment]
Selfhosting PR: https://github.com/FredBoat/fredboat.com/pull/14

Looking for feedback for wording, formatting, and ofc the tutorial itself.

The CI builds for "stable" and "dev" branches aren't exporting any docker files yet, use these links instead:

https://ci.fredboat.com/viewLog.html?buildTypeId=FredBoat_Build&buildId=lastSuccessful&buildBranch=refs/heads/feature/docker&tab=artifacts&guest=1
```sh
wget https://ci.fredboat.com/guestAuth/repository/download/FredBoat_Build/.lastSuccessful/docker-compose.yml?branch=refs/heads/feature/docker -O docker-compose.yml
```
Docker images aren't up on the official fredboat account yet. Replace them with these inofficial ones (there is _definitely_ no monero miner inside of those ( ͡° ͜ʖ ͡°) ) in the docker-compose.yml:
~~fredboat/postgres~~ -> napstr/postgres
~~fredboat/fredboat:stable~~ / ~~fredboat/fredboat:dev~~ -> napstr/fredboat:feature_docker

**Comment by babdab9** [comment]
Will that remove jars and we will have to use docker?

**Comment by napstr** [comment]
I don't understand your question.

**Comment by napstr** [comment]
FredBoat is still a Java project so ultimately there is a jar running _somewhere_. So no, this will not "remove the jars". However using docker will spare users the hassle of building the jar and setting it up and installing java. That's explained in detail in the linked PR to the website that updates the selfhosting docs.

**Comment by babdab9** [comment]
First of all, I read the discussion again and found out that my question is out of topic
To clarify, I meant if we could still use fredboat's CI site to download .jar files to run our bots, or we would have to use Dicker to run our bots.
**Stating again, my question was off-topic**

**Comment by napstr** [comment]
You can still download the jar from the CI servers or build it yourself from the source code. However FredBoat will require a PostgreSQL database to run.

**Comment by napstr** [comment]
Btw here's the preview link for the selfhosting docs:

https://deploy-preview-14--fredboatcom.netlify.com/docs/selfhosting

**Comment by babdab9** [comment]
When will this option be out of beta (probably already cuz it is merged but I still ask)

**Comment by napstr** [comment]
We don't do ETAs.

**Pull request merged**
