### PR TITLE
Add debug Command

### PR DESCRIPTION
**Pull request by Nanabell**
For now this is mainly for feedback as i dont think this is optimized well. Its just so we all can see what i code at 5 in the morning

### CODE REVIEW

**Comment by Nanabell** [comment]
Should I use I18n strings for this? While it now is a DJ level command for the current guild it is still just a debug command so I don't think we NEED translations but will add them ofc if wanted

**Comment by Frederikam** [comment]
No I18n required. We don't do that for ;;mstats for instance

**Comment by Nanabell** [comment]
oh ? I thought we're gonna add the lavalink stuff as well

**Comment by Frederikam** [comment]
@Nanabell I forgot about that- Btw we somehow failed the build https://travis-ci.org/Frederikam/FredBoat/builds/282634021?utm_source=email&utm_medium=notification

**Comment by Nanabell** [comment]
wot :thonk: 
image

**Comment by Frederikam** [comment]
That's hte PR buld. Something about the rebase killed it

**Comment by Nanabell** [comment]
image
:fry:

**Comment by Nanabell** [comment]
i dont wanna open yet another pr for that. u gonna fix it quickly on your end ?

**Comment by Frederikam** [comment]
Yeah give me a moment

**Pull request merged**
